# Launch an Amazon Linux instance in AWS
---
- name: Create vpn instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: add localhost to env group to pull in group vars
      add_host:
        name: localhost
        groups: "{{ env }}"

    - name: Launch instances
      ec2: 
        key_name: "{{ vpn_key_name }}"
        group: "{{ vpn_sg_name }}"
        instance_type: "{{ vpn_instance_type }}"
        image: "{{ vpn_base_image }}"
        wait: true
        region: "{{ vpc_region }}"
        vpc_subnet_id: "{{ vpn_vpc_subnet_id }}"
        assign_public_ip: no
        termination_protection: yes
        instance_tags:
            Name: "{{ env }}-vpn"
            Env: "{{ env }}"
            AnsibleRole: "vpn"
            Backup: backup
            Monitor: true
        exact_count: 1
        count_tag:
            Name: "{{ env }}-vpn"
            Env: "{{ env }}"
            AnsibleRole: "vpn"
        instance_profile_name: "{{ vpn_instance_profile_name }}"
        source_dest_check: no
      register: ec2
    - name: debug
      debug:
        var: ec2
    - name: Wait for ssh to come up
      wait_for:
        host: "{{ item['private_ip'] }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.tagged_instances }}" 
    - name: associate the vpn's eip
      ec2_eip:
        device_id: "{{ ec2.instance_ids[0] }}"
        ip: "{{ vpn_elastic_ip }}"
        region: us-east-1
